import { useEffect, useState } from 'react'
import { ArrowDownRight, ArrowUpRight, Code2, ExternalLink, Mail, Menu, Phone, Send, X } from 'lucide-react'
import './App.css'

const navItems = [['Accueil', 'home'], ['À propos', 'about'], ['Compétences', 'skills'], ['Expériences', 'experience'], ['Projets', 'projects'], ['Contact', 'contact']]
const skills = { Frontend: ['React.js', 'Next.js', 'Vue.js', 'Angular', 'HTML5', 'CSS3', 'JavaScript', 'TypeScript'], 'CSS & UI': ['Tailwind CSS', 'Bootstrap', 'Material-UI'], Backend: ['Node.js / Express', 'Laravel', 'Spring Boot', 'Django', 'NestJS'], 'Data & DevOps': ['MySQL', 'PostgreSQL', 'MongoDB', 'Redis', 'Git', 'Docker', 'CI/CD', 'AWS', 'Vercel'] }
const projects = [{ number: '01', title: 'Jojma Group ERP', description: 'Système de gestion des activités internes et des processus métiers.', stack: 'Spring Boot · Angular · MongoDB · TailwindCSS', accent: 'from-ocean-700/80 to-[#0b263a]' }, { number: '02', title: 'Link-Edu', description: 'Application web de gestion et de communication pour un établissement scolaire.', stack: 'Laravel · MySQL · React · TailwindCSS', accent: 'from-[#164d5c] to-[#123043]' }]

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [mouse, setMouse] = useState({ x: 50, y: 50 })
  useEffect(() => { const move = (event) => setMouse({ x: (event.clientX / window.innerWidth) * 100, y: (event.clientY / window.innerHeight) * 100 }); window.addEventListener('mousemove', move); return () => window.removeEventListener('mousemove', move) }, [])
  const closeMenu = () => setMenuOpen(false)

  return <div className="min-h-screen overflow-hidden bg-ocean-950 text-slate-100" style={{ '--mouse-x': `${mouse.x}%`, '--mouse-y': `${mouse.y}%` }}>
    <div className="pointer-glow" aria-hidden="true" />
    <header className="fixed inset-x-0 top-0 z-40 px-5 py-5 md:px-10"><nav className="mx-auto flex max-w-6xl items-center justify-between rounded-full border border-white/10 bg-ocean-950/75 px-4 py-3 shadow-2xl backdrop-blur-xl md:px-6"><a href="#home" className="font-display text-lg font-semibold tracking-tight" onClick={closeMenu}>YB<span className="text-ocean-300">.</span></a><div className="hidden items-center gap-7 text-sm text-slate-400 md:flex">{navItems.map(([label, id]) => <a key={id} href={`#${id}`} className="transition-colors hover:text-ocean-300">{label}</a>)}</div><button className="icon-button md:hidden" aria-label="Ouvrir le menu" onClick={() => setMenuOpen(true)}><Menu size={20} /></button><a href="#contact" className="hidden items-center gap-2 rounded-full bg-ocean-500 px-4 py-2 text-sm font-semibold text-ocean-950 transition-all hover:bg-ocean-300 hover:shadow-glow md:flex">Parlons-en <ArrowUpRight size={15} /></a></nav></header>
    {menuOpen && <div className="fixed inset-0 z-50 flex flex-col bg-ocean-950/90 p-6 backdrop-blur-2xl md:hidden"><div className="flex items-center justify-between"><span className="font-display text-lg font-semibold">YB<span className="text-ocean-300">.</span></span><button className="icon-button" onClick={closeMenu} aria-label="Fermer le menu"><X size={20} /></button></div><div className="mt-20 flex flex-col gap-5 font-display text-4xl font-medium">{navItems.map(([label, id], index) => <a className="menu-link" style={{ animationDelay: `${index * 55}ms` }} key={id} href={`#${id}`} onClick={closeMenu}><span className="mr-3 text-sm text-ocean-300">0{index + 1}</span>{label}</a>)}</div><div className="mt-auto flex gap-4 text-slate-400"><a href="mailto:baroutyoussef@gmail.com"><Mail size={19} /></a><a href="https://github.com/youssefbarout" target="_blank" rel="noreferrer"><ExternalLink size={19} /></a><a href="https://linkedin.com/in/youssefbarout" target="_blank" rel="noreferrer"><ExternalLink size={19} /></a></div></div>}
    <main>
      <section id="home" className="relative mx-auto flex min-h-screen max-w-6xl items-center px-5 pb-20 pt-36 md:px-10"><div className="max-w-4xl animate-rise"><p className="mb-7 flex items-center gap-3 text-sm font-semibold uppercase tracking-[0.28em] text-ocean-300"><span className="h-px w-10 bg-ocean-300" /> Disponible pour de nouveaux projets</p><h1 className="max-w-4xl font-display text-5xl font-semibold leading-[0.96] tracking-[-0.06em] text-white sm:text-7xl md:text-8xl">Je construis des <span className="text-ocean-300">expériences</span> digitales utiles.</h1><p className="mt-8 max-w-xl text-lg leading-relaxed text-slate-400">Développeur Full-Stack Junior basé au Maroc. Je transforme des idées complexes en interfaces simples, rapides et mémorables.</p><div className="mt-10 flex flex-wrap items-center gap-4"><a href="#projects" className="button-primary">Voir mes projets <ArrowDownRight size={17} /></a><a href="#about" className="button-ghost">Découvrir mon profil</a></div></div><div className="absolute bottom-10 right-8 hidden flex-col items-center gap-3 text-[10px] uppercase tracking-[0.3em] text-slate-500 md:flex"><span className="h-14 w-px bg-gradient-to-b from-transparent via-ocean-500 to-transparent" /> Scroll pour explorer</div></section>
      <section id="about" className="border-y border-white/10 bg-[#081c2a]/65 px-5 py-24 md:px-10 md:py-32"><div className="mx-auto grid max-w-6xl gap-14 md:grid-cols-[0.8fr_1.2fr] md:items-end"><div><p className="eyebrow">01 / À propos</p><h2 className="section-title">Curieux par nature.<br /><span className="text-ocean-300">Précis par choix.</span></h2></div><div><p className="text-xl leading-relaxed text-slate-300">Fraîchement diplômé en Développement Digital à l'ISGI, je conçois des produits qui trouvent le juste équilibre entre logique technique et qualité d'expérience.</p><p className="mt-6 max-w-2xl leading-relaxed text-slate-500">Dynamique, rigoureux et orienté solutions, j'aime comprendre le pourquoi avant de construire le comment. Chaque ligne de code doit servir une intention claire.</p><div className="mt-8 grid grid-cols-2 gap-6 border-t border-white/10 pt-6 text-sm text-slate-400 sm:grid-cols-3"><div><strong className="block font-display text-3xl text-white">02</strong>projets principaux</div><div><strong className="block font-display text-3xl text-white">04+</strong>années d'apprentissage</div><div><strong className="block font-display text-3xl text-white">∞</strong>envie de progresser</div></div></div></div></section>
      <section id="skills" className="mx-auto max-w-6xl px-5 py-24 md:px-10 md:py-32"><p className="eyebrow">02 / Compétences</p><div className="mb-14 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="section-title">Les outils pour<br /><span className="text-ocean-300">donner vie aux idées.</span></h2><p className="max-w-sm text-sm leading-relaxed text-slate-500">Une boîte à outils polyvalente pour couvrir toute la chaîne, de l'interface au déploiement.</p></div><div className="grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-2">{Object.entries(skills).map(([category, items]) => <div className="bg-ocean-950 p-7 transition-colors hover:bg-[#0b2638]" key={category}><div className="mb-8 flex items-center justify-between"><h3 className="font-display text-xl font-medium text-white">{category}</h3><Code2 size={18} className="text-ocean-300" /></div><div className="flex flex-wrap gap-2">{items.map((item) => <span className="tag" key={item}>{item}</span>)}</div></div>)}</div></section>
      <section id="experience" className="border-y border-white/10 bg-[#081c2a]/65 px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-6xl"><p className="eyebrow">03 / Expériences</p><div className="mt-14 divide-y divide-white/10">{[{date: '2024 — 2025', role: 'Full Stack Developer · Stage', company: 'Jojma Group', text: "Développement d'un ERP pour la gestion des activités internes. Conception de modules backend/frontend, tests, correction de bugs et optimisation."}, {date: '2023 — 2024', role: 'Stagiaire Administratif', company: "Administration de l'ISGI · OFPPT", text: "Gestion des inscriptions et réinscriptions, organisation de la base de données des nouveaux inscrits et support administratif."}].map((job) => <article className="grid gap-5 py-9 md:grid-cols-[0.25fr_0.75fr]" key={job.company}><p className="text-sm text-ocean-300">{job.date}</p><div><h3 className="font-display text-2xl text-white">{job.role}</h3><p className="mt-1 text-slate-500">{job.company}</p><p className="mt-5 max-w-2xl leading-relaxed text-slate-400">{job.text}</p></div></article>)}</div><div className="mt-16 border-t border-white/10 pt-10"><p className="eyebrow">Diplômes & certifications</p><div className="mt-7 grid gap-3 md:grid-cols-3">{['Diplôme TS Digital Development · ISGI (OFPPT)', 'Attestation de Stage Développement Web Full Stack · Jojma Group', 'Attestation Hackathon Semaine Régionale du Digital · ISGI'].map((credential) => <div className="flex gap-3 rounded-xl border border-white/10 bg-ocean-950/60 p-5 text-sm leading-relaxed text-slate-300" key={credential}><span className="mt-1 text-ocean-300">✓</span>{credential}</div>)}</div></div></div></section>
      <section id="projects" className="mx-auto max-w-6xl px-5 py-24 md:px-10 md:py-32"><div className="mb-14 flex items-end justify-between"><div><p className="eyebrow">04 / Projets sélectionnés</p><h2 className="section-title mt-5">Des projets qui<br /><span className="text-ocean-300">font avancer.</span></h2></div><span className="hidden font-display text-6xl text-white/10 md:block">02</span></div><div className="grid gap-6 md:grid-cols-2">{projects.map((project) => <article className={`group relative min-h-[390px] overflow-hidden rounded-2xl bg-gradient-to-br ${project.accent} p-7 transition-all duration-500 hover:-translate-y-2 hover:shadow-glow`} key={project.title}><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(131,216,237,.2),transparent_32%)] opacity-60 transition-opacity group-hover:opacity-100" /><div className="relative flex h-full flex-col justify-between"><div className="flex items-start justify-between"><span className="font-display text-sm text-ocean-300">{project.number}</span><div className="rounded-full border border-white/20 p-2 text-white transition-transform group-hover:rotate-45"><ArrowUpRight size={17} /></div></div><div><h3 className="font-display text-3xl font-medium text-white">{project.title}</h3><p className="mt-3 max-w-sm text-slate-300">{project.description}</p><p className="mt-7 text-xs uppercase tracking-wider text-ocean-300">{project.stack}</p></div></div></article>)}</div></section>
      <section id="contact" className="relative overflow-hidden border-t border-white/10 px-5 py-28 text-center md:px-10 md:py-40"><div className="relative z-10 mx-auto max-w-3xl"><p className="eyebrow justify-center">05 / Contact</p><h2 className="mt-6 font-display text-5xl font-semibold tracking-[-0.06em] text-white sm:text-7xl">Construisons quelque chose de <span className="text-ocean-300">singulier.</span></h2><p className="mx-auto mt-7 max-w-lg text-slate-400">Une idée, un projet ou simplement envie d'échanger ? Ma boîte mail est ouverte.</p><a href="mailto:baroutyoussef@gmail.com" className="button-primary mt-9">Me contacter <Send size={16} /></a></div><div className="absolute inset-x-0 bottom-[-50%] mx-auto h-full w-3/4 rounded-full bg-ocean-700/20 blur-[120px]" /></section>
    </main>
    <footer className="mx-auto flex max-w-6xl flex-col gap-5 border-t border-white/10 px-5 py-8 text-sm text-slate-500 md:flex-row md:items-center md:justify-between md:px-10"><span>© 2025 Youssef Barout. Tous droits réservés.</span><div className="flex items-center gap-5"><a className="transition-colors hover:text-ocean-300" href="tel:+212668066272"><Phone size={16} /></a><a className="transition-colors hover:text-ocean-300" href="mailto:baroutyoussef@gmail.com"><Mail size={16} /></a><a className="transition-colors hover:text-ocean-300" href="https://github.com/youssefbarout" target="_blank" rel="noreferrer"><ExternalLink size={16} /></a><a className="transition-colors hover:text-ocean-300" href="https://linkedin.com/in/youssefbarout" target="_blank" rel="noreferrer"><ExternalLink size={16} /></a></div></footer>
  </div>
}

export default App
