import { useEffect, useState } from 'react'
import { ArrowDownRight, ArrowUpRight, Code2, ExternalLink, Mail, Menu, Phone, Send, X } from 'lucide-react'
import './App.css'
import profileImage from './assets/profile.png'

const navItems = [['Accueil', 'Home', 'home'], ['Travaux', 'Work', 'projects'], ['Parcours', 'Journey', 'experience'], ['Outils', 'Tools', 'skills'], ['Contact', 'Contact', 'contact']]
const skills = { Frontend: ['React.js', 'Next.js', 'Vue.js', 'Angular', 'HTML5', 'CSS3', 'JavaScript', 'TypeScript'], 'CSS & UI': ['Tailwind CSS', 'Bootstrap', 'Material-UI'], Backend: ['Node.js / Express', 'Laravel', 'Spring Boot', 'Django', 'NestJS'], 'Data & DevOps': ['MySQL', 'PostgreSQL', 'MongoDB', 'Redis', 'Git', 'Docker', 'CI/CD', 'AWS', 'Vercel'] }
const projects = [{ number: '01', title: 'Jojma Group ERP', description: 'Système de gestion des activités internes et des processus métiers.', stack: 'Spring Boot · Angular · MongoDB · TailwindCSS', accent: 'from-ocean-700/80 to-[#2a211b]' }, { number: '02', title: 'Link-Edu', description: 'Application web de gestion et de communication pour un établissement scolaire.', stack: 'Laravel · MySQL · React · TailwindCSS', accent: 'from-[#5a4635] to-[#30261f]' }]

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [language, setLanguage] = useState('fr')
  const [mouse, setMouse] = useState({ x: 50, y: 50 })
  useEffect(() => { const move = (event) => setMouse({ x: (event.clientX / window.innerWidth) * 100, y: (event.clientY / window.innerHeight) * 100 }); window.addEventListener('mousemove', move); return () => window.removeEventListener('mousemove', move) }, [])
  useEffect(() => { document.body.style.overflow = menuOpen ? 'hidden' : ''; return () => { document.body.style.overflow = '' } }, [menuOpen])
  const closeMenu = () => setMenuOpen(false)
  const copy = language === 'fr' ? {
    available: 'Disponible pour de nouveaux projets', hero: 'Je construis des', heroAccent: 'expériences', heroEnd: 'digitales utiles.',
    intro: 'Développeur Full-Stack Junior basé au Maroc. Je transforme des idées complexes en interfaces simples, rapides et mémorables.',
    projectsButton: 'Voir mes projets', profileButton: 'Découvrir mon profil', scroll: 'Scroll pour explorer',
    about: 'À propos', aboutTitle: 'Curieux par nature.', aboutAccent: 'Précis par choix.',
    aboutLead: "Fraîchement diplômé en Développement Digital à l'ISGI, je conçois des produits qui trouvent le juste équilibre entre logique technique et qualité d'expérience.",
    aboutText: "Dynamique, rigoureux et orienté solutions, j'aime comprendre le pourquoi avant de construire le comment. Chaque ligne de code doit servir une intention claire.",
    projectsCount: 'projets principaux', learning: "années d'apprentissage", growth: 'envie de progresser', skills: 'Compétences',
    skillsTitle: 'Les outils pour', skillsAccent: 'donner vie aux idées.', skillsText: "Une boîte à outils polyvalente pour couvrir toute la chaîne, de l'interface au déploiement.",
    experience: 'Expériences', credentials: 'Diplômes & certifications', selectedProjects: 'Projets sélectionnés',
    projectTitle: 'Des projets qui', projectAccent: 'font avancer.', contact: 'Contact', contactTitle: 'Démarrer une conversation',
    contactText: 'Ouverts aux stages, missions freelance et postes à temps plein. Je réponds généralement sous 24 heures.',
    name: 'Nom', message: 'Message', send: 'Envoyer le message', availableLabel: 'Disponible', follow: 'À suivre',
    track: 'GitHub', linkedin: 'LinkedIn', footer: 'Tous droits réservés.'
  } : {
    available: 'Available for new projects', hero: 'I build', heroAccent: 'useful digital', heroEnd: 'experiences.',
    intro: 'Junior Full-Stack Developer based in Morocco. I turn complex ideas into simple, fast and memorable interfaces.',
    projectsButton: 'View my work', profileButton: 'Discover my profile', scroll: 'Scroll to explore',
    about: 'About', aboutTitle: 'Naturally curious.', aboutAccent: 'Precise by choice.',
    aboutLead: 'Recently graduated in Digital Development from ISGI, I design products that balance technical logic with a quality user experience.',
    aboutText: 'Dynamic, rigorous and solution-oriented, I like to understand the why before building the how. Every line of code should serve a clear purpose.',
    projectsCount: 'main projects', learning: 'years of learning', growth: 'desire to grow', skills: 'Skills',
    skillsTitle: 'The tools to', skillsAccent: 'bring ideas to life.', skillsText: 'A versatile toolkit covering the entire journey, from interface design to deployment.',
    experience: 'Experience', credentials: 'Degrees & certifications', selectedProjects: 'Selected projects',
    projectTitle: 'Projects that', projectAccent: 'move things forward.', contact: 'Contact', contactTitle: 'Start a conversation',
    contactText: 'Open to internships, freelance missions and full-time positions. I usually reply within 24 hours.',
    name: 'Name', message: 'Message', send: 'Send message', availableLabel: 'Available', follow: 'Follow',
    track: 'GitHub', linkedin: 'LinkedIn', footer: 'All rights reserved.'
  }

  return <div className="min-h-screen overflow-hidden bg-ocean-950 text-slate-100" style={{ '--mouse-x': `${mouse.x}%`, '--mouse-y': `${mouse.y}%` }}>
    <div className="pointer-glow" aria-hidden="true" />
    <button className="icon-button menu-toggle menu-floating" aria-label="Ouvrir le menu" onClick={() => setMenuOpen(true)}><Menu size={24} /></button>
    {menuOpen && <div className="menu-overlay fixed inset-0 z-50 flex flex-col p-6 backdrop-blur-2xl"><div className="flex items-center justify-end"><button className="icon-button menu-close" onClick={closeMenu} aria-label={language === 'fr' ? 'Fermer le menu' : 'Close menu'}><X size={24} /></button></div><div className="menu-navigation mx-auto flex w-full max-w-xl flex-col font-display">{navItems.map(([labelFr, labelEn, id], index) => <a className="menu-link" style={{ animationDelay: `${index * 55}ms` }} key={id} href={`#${id}`} onClick={closeMenu}><span className="menu-number">{String(index + 1).padStart(2, '0')}</span><span>{language === 'fr' ? labelFr : labelEn}</span></a>)}</div><div className="menu-footer"><button className="language-switch" type="button" onClick={() => setLanguage((current) => current === 'fr' ? 'en' : 'fr')}>{language === 'fr' ? 'Switch to English' : 'Passer en français'}</button></div></div>}
    <main>
      <section id="home" className="hero-section relative mx-auto flex min-h-screen max-w-7xl items-center overflow-hidden px-5 pb-20 pt-28 md:px-10"><div className="hero-code-lines" aria-hidden="true"><span>{'<header>'}</span><span>{'  <h1>Youssef Barout</h1>'}</span><span>{'  <p>Full-Stack Developer</p>'}</span><span>{'</header>'}</span></div><div className="hero-word" aria-hidden="true">PORTFOLIO</div><div className="relative z-10 max-w-2xl animate-rise"><p className="hero-name">Youssef Barout</p><p className="hero-role">DÉVELOPPEUR FULL-STACK JUNIOR</p><h1 className="hero-heading">{copy.hero} <span>{copy.heroAccent}</span> {copy.heroEnd}</h1><p className="hero-description">{copy.intro}</p><a href="#contact" className="button-primary hero-cta">Démarrer une conversation <ArrowDownRight size={17} /></a></div><div className="hero-portrait-wrap" aria-hidden="true"><div className="hero-portrait-frame"><img src={profileImage} alt="" /></div></div><div className="absolute bottom-10 left-5 hidden text-[10px] uppercase tracking-[0.3em] text-slate-500 md:block">{copy.scroll}</div></section>
      <section id="about" className="border-y border-white/10 bg-[#211c18]/65 px-5 py-24 md:px-10 md:py-32"><div className="mx-auto grid max-w-6xl gap-14 md:grid-cols-[0.8fr_1.2fr] md:items-end"><div><p className="eyebrow">01 / {copy.about}</p><h2 className="section-title">{copy.aboutTitle}<br /><span className="text-ocean-300">{copy.aboutAccent}</span></h2></div><div><p className="text-xl leading-relaxed text-slate-300">{copy.aboutLead}</p><p className="mt-6 max-w-2xl leading-relaxed text-slate-500">{copy.aboutText}</p><div className="mt-8 grid grid-cols-2 gap-6 border-t border-white/10 pt-6 text-sm text-slate-400 sm:grid-cols-3"><div><strong className="block font-display text-3xl text-white">02</strong>{copy.projectsCount}</div><div><strong className="block font-display text-3xl text-white">04+</strong>{copy.learning}</div><div><strong className="block font-display text-3xl text-white">∞</strong>{copy.growth}</div></div></div></div></section>
      <section id="skills" className="mx-auto max-w-6xl px-5 py-24 md:px-10 md:py-32"><p className="eyebrow">02 / {copy.skills}</p><div className="mb-14 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="section-title">{copy.skillsTitle}<br /><span className="text-ocean-300">{copy.skillsAccent}</span></h2><p className="max-w-sm text-sm leading-relaxed text-slate-500">{copy.skillsText}</p></div><div className="grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-2">{Object.entries(skills).map(([category, items]) => <div className="bg-ocean-950 p-7 transition-colors hover:bg-[#0b2638]" key={category}><div className="mb-8 flex items-center justify-between"><h3 className="font-display text-xl font-medium text-white">{category}</h3><Code2 size={18} className="text-ocean-300" /></div><div className="flex flex-wrap gap-2">{items.map((item) => <span className="tag" key={item}>{item}</span>)}</div></div>)}</div></section>
      <section id="experience" className="border-y border-white/10 bg-[#211c18]/65 px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-6xl"><p className="eyebrow">03 / {copy.experience}</p><div className="mt-14 divide-y divide-white/10">{[{date: '2024 — 2025', role: language === 'fr' ? 'Full Stack Developer · Stage' : 'Full Stack Developer · Internship', company: 'Jojma Group', text: language === 'fr' ? "Développement d'un ERP pour la gestion des activités internes. Conception de modules backend/frontend, tests, correction de bugs et optimisation." : 'Developed an ERP for managing internal activities. Designed backend/frontend modules, tested features, fixed bugs and optimized performance.'}, {date: '2023 — 2024', role: language === 'fr' ? 'Stagiaire Administratif' : 'Administrative Intern', company: "Administration de l'ISGI · OFPPT", text: language === 'fr' ? "Gestion des inscriptions et réinscriptions, organisation de la base de données des nouveaux inscrits et support administratif." : 'Managed registrations and re-registrations, organized the database of new students and provided administrative support.'}].map((job) => <article className="grid gap-5 py-9 md:grid-cols-[0.25fr_0.75fr]" key={job.company}><p className="text-sm text-ocean-300">{job.date}</p><div><h3 className="font-display text-2xl text-white">{job.role}</h3><p className="mt-1 text-slate-500">{job.company}</p><p className="mt-5 max-w-2xl leading-relaxed text-slate-400">{job.text}</p></div></article>)}</div><div className="mt-16 border-t border-white/10 pt-10"><p className="eyebrow">{copy.credentials}</p><div className="mt-7 grid gap-3 md:grid-cols-3">{(language === 'fr' ? ['Diplôme TS Digital Development · ISGI (OFPPT)', 'Attestation de Stage Développement Web Full Stack · Jojma Group', 'Attestation Hackathon Semaine Régionale du Digital · ISGI'] : ['Digital Development Technician Diploma · ISGI (OFPPT)', 'Full-Stack Web Development Internship Certificate · Jojma Group', 'Regional Digital Week Hackathon Certificate · ISGI']).map((credential) => <div className="flex gap-3 rounded-xl border border-white/10 bg-ocean-950/60 p-5 text-sm leading-relaxed text-slate-300" key={credential}><span className="mt-1 text-ocean-300">✓</span>{credential}</div>)}</div></div></div></section>
      <section id="projects" className="mx-auto max-w-6xl px-5 py-24 md:px-10 md:py-32"><div className="mb-14 flex items-end justify-between"><div><p className="eyebrow">04 / {copy.selectedProjects}</p><h2 className="section-title mt-5">{copy.projectTitle}<br /><span className="text-ocean-300">{copy.projectAccent}</span></h2></div><span className="hidden font-display text-6xl text-white/10 md:block">02</span></div><div className="grid gap-6 md:grid-cols-2">{projects.map((project) => <article className={`group relative min-h-[390px] overflow-hidden rounded-2xl bg-gradient-to-br ${project.accent} p-7 transition-all duration-500 hover:-translate-y-2 hover:shadow-glow`} key={project.title}><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(131,216,237,.2),transparent_32%)] opacity-60 transition-opacity group-hover:opacity-100" /><div className="relative flex h-full flex-col justify-between"><div className="flex items-start justify-between"><span className="font-display text-sm text-ocean-300">{project.number}</span><div className="rounded-full border border-white/20 p-2 text-white transition-transform group-hover:rotate-45"><ArrowUpRight size={17} /></div></div><div><h3 className="font-display text-3xl font-medium text-white">{project.title}</h3><p className="mt-3 max-w-sm text-slate-300">{language === 'fr' ? project.description : project.title === 'Jojma Group ERP' ? 'Internal activity management and business process system.' : 'Web management and communication application for a school.'}</p><p className="mt-7 text-xs uppercase tracking-wider text-ocean-300">{project.stack}</p></div></div></article>)}</div></section>
      <section id="contact" className="contact-section relative overflow-hidden border-t border-white/10 px-5 py-24 md:px-10 md:py-32"><div className="relative z-10 mx-auto max-w-6xl"><p className="eyebrow">05 / {copy.contact}</p><h2 className="contact-title mt-6 max-w-3xl font-display text-5xl font-semibold tracking-[-0.07em] text-white sm:text-7xl">{copy.contactTitle}</h2><p className="mt-5 max-w-xl text-sm leading-relaxed text-slate-400">{copy.contactText}</p><a className="contact-email mt-7 inline-block" href="mailto:baroutyoussef@gmail.com">baroutyoussef@gmail.com</a><div className="mt-10 border-t border-white/15 pt-6"><div className="grid gap-10 md:grid-cols-[1fr_.9fr]"><form className="contact-form grid gap-4" action="mailto:baroutyoussef@gmail.com" method="post" encType="text/plain"><label htmlFor="name">{copy.name}</label><input id="name" name="name" type="text" required /><label htmlFor="email">Email</label><input id="email" name="email" type="email" required /><label htmlFor="message">{copy.message}</label><textarea id="message" name="message" rows="5" required /><button className="button-primary contact-submit" type="submit">{copy.send} <Send size={15} /></button></form><div className="contact-details grid content-start gap-7 text-xs"><div><span>{copy.availableLabel}</span><p>Casablanca, Morocco<br />Africa / Casablanca</p></div><div><span>{copy.follow}</span><div className="grid gap-1"><a href="https://github.com/youssefbarout" target="_blank" rel="noreferrer">{copy.track} ↗</a><a href="https://linkedin.com/in/youssefbarout" target="_blank" rel="noreferrer">{copy.linkedin} ↗</a></div></div></div></div></div></div><div className="absolute inset-x-0 bottom-[-50%] mx-auto h-full w-3/4 rounded-full bg-ocean-700/20 blur-[120px]" /></section>
    </main>
    <footer className="mx-auto flex max-w-6xl flex-col gap-5 border-t border-white/10 px-5 py-8 text-sm text-slate-500 md:flex-row md:items-center md:justify-between md:px-10"><span>© 2025 Youssef Barout. {copy.footer}</span><div className="flex items-center gap-5"><a className="transition-colors hover:text-ocean-300" href="tel:+212668066272"><Phone size={16} /></a><a className="transition-colors hover:text-ocean-300" href="mailto:baroutyoussef@gmail.com"><Mail size={16} /></a><a className="transition-colors hover:text-ocean-300" href="https://github.com/youssefbarout" target="_blank" rel="noreferrer"><ExternalLink size={16} /></a><a className="transition-colors hover:text-ocean-300" href="https://linkedin.com/in/youssefbarout" target="_blank" rel="noreferrer"><ExternalLink size={16} /></a></div></footer>
  </div>
}

export default App
